from qgis.PyQt import QtCore, QtGui, QtWidgets
from src.widgets.custom.QLinkedCombobox import QLinkedCombobox


class Ui_ParcelFinderDialog:
    def setupUi(self, ParcelFinderDialog):
        ParcelFinderDialog.setObjectName("ParcelFinderDialog")
        ParcelFinderDialog.resize(250, 392)
        ParcelFinderDialog.setMaximumSize(QtCore.QSize(250, 400))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(ParcelFinderDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.voivodeshipGroup = QtWidgets.QFrame(ParcelFinderDialog)
        self.voivodeshipGroup.setEnabled(True)
        self.voivodeshipGroup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.voivodeshipGroup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.voivodeshipGroup.setObjectName("voivodeshipGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.voivodeshipGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.voivodeshipComboBoxLabel = QtWidgets.QLabel(self.voivodeshipGroup)
        self.voivodeshipComboBoxLabel.setObjectName("voivodeshipComboBoxLabel")
        self.verticalLayout.addWidget(self.voivodeshipComboBoxLabel)
        self.voivodeshipComboBox = QLinkedCombobox(self.voivodeshipGroup)
        self.voivodeshipComboBox.setEnabled(False)
        self.voivodeshipComboBox.setToolTip("")
        self.voivodeshipComboBox.setEditable(True)
        self.voivodeshipComboBox.setFrame(True)
        self.voivodeshipComboBox.setObjectName("voivodeshipComboBox")
        self.verticalLayout.addWidget(self.voivodeshipComboBox)
        self.verticalLayout_6.addWidget(self.voivodeshipGroup)
        self.countyGroup = QtWidgets.QFrame(ParcelFinderDialog)
        self.countyGroup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.countyGroup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.countyGroup.setObjectName("countyGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.countyGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.countyComboBoxLabel = QtWidgets.QLabel(self.countyGroup)
        self.countyComboBoxLabel.setObjectName("countyComboBoxLabel")
        self.verticalLayout_2.addWidget(self.countyComboBoxLabel)
        self.countyComboBox = QLinkedCombobox(self.countyGroup)
        self.countyComboBox.setEnabled(False)
        self.countyComboBox.setToolTip("")
        self.countyComboBox.setEditable(True)
        self.countyComboBox.setObjectName("countyComboBox")
        self.verticalLayout_2.addWidget(self.countyComboBox)
        self.verticalLayout_6.addWidget(self.countyGroup)
        self.communeGroup = QtWidgets.QFrame(ParcelFinderDialog)
        self.communeGroup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.communeGroup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.communeGroup.setObjectName("communeGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.communeGroup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.communeComboBoxLabel = QtWidgets.QLabel(self.communeGroup)
        self.communeComboBoxLabel.setObjectName("communeComboBoxLabel")
        self.verticalLayout_3.addWidget(self.communeComboBoxLabel)
        self.communeComboBox = QLinkedCombobox(self.communeGroup)
        self.communeComboBox.setEnabled(False)
        self.communeComboBox.setToolTip("")
        self.communeComboBox.setEditable(True)
        self.communeComboBox.setObjectName("communeComboBox")
        self.verticalLayout_3.addWidget(self.communeComboBox)
        self.verticalLayout_6.addWidget(self.communeGroup)
        self.regionGroup = QtWidgets.QFrame(ParcelFinderDialog)
        self.regionGroup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.regionGroup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.regionGroup.setObjectName("regionGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.regionGroup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.regionComboBoxLabel = QtWidgets.QLabel(self.regionGroup)
        self.regionComboBoxLabel.setMaximumSize(QtCore.QSize(250, 60))
        self.regionComboBoxLabel.setObjectName("regionComboBoxLabel")
        self.verticalLayout_4.addWidget(self.regionComboBoxLabel)
        self.regionComboBox = QLinkedCombobox(self.regionGroup)
        self.regionComboBox.setEnabled(False)
        self.regionComboBox.setToolTip("")
        self.regionComboBox.setEditable(True)
        self.regionComboBox.setObjectName("regionComboBox")
        self.verticalLayout_4.addWidget(self.regionComboBox)
        self.verticalLayout_6.addWidget(self.regionGroup)
        self.parcelGroup = QtWidgets.QFrame(ParcelFinderDialog)
        self.parcelGroup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parcelGroup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parcelGroup.setObjectName("parcelGroup")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.parcelGroup)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.parcelComboBoxLabel = QtWidgets.QLabel(self.parcelGroup)
        self.parcelComboBoxLabel.setObjectName("parcelComboBoxLabel")
        self.verticalLayout_5.addWidget(self.parcelComboBoxLabel)
        self.parcelComboBox = QtWidgets.QComboBox(self.parcelGroup)
        self.parcelComboBox.setEnabled(False)
        self.parcelComboBox.setToolTip("")
        self.parcelComboBox.setEditable(True)
        self.parcelComboBox.setObjectName("parcelComboBox")
        self.verticalLayout_5.addWidget(self.parcelComboBox)
        self.verticalLayout_6.addWidget(self.parcelGroup)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(ParcelFinderDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.parcelZoomButton = QtWidgets.QPushButton(self.frame)
        self.parcelZoomButton.setEnabled(False)
        self.parcelZoomButton.setObjectName("parcelZoomButton")
        self.horizontalLayout.addWidget(self.parcelZoomButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_6.addWidget(self.frame)

        self.retranslateUi(ParcelFinderDialog)
        QtCore.QMetaObject.connectSlotsByName(ParcelFinderDialog)
        ParcelFinderDialog.setTabOrder(self.voivodeshipComboBox, self.countyComboBox)
        ParcelFinderDialog.setTabOrder(self.countyComboBox, self.communeComboBox)
        ParcelFinderDialog.setTabOrder(self.communeComboBox, self.regionComboBox)
        ParcelFinderDialog.setTabOrder(self.regionComboBox, self.parcelComboBox)
        ParcelFinderDialog.setTabOrder(self.parcelComboBox, self.parcelZoomButton)

    def retranslateUi(self, ParcelFinderDialog):
        _translate = QtCore.QCoreApplication.translate
        ParcelFinderDialog.setWindowTitle(_translate("ParcelFinderDialog", "Dialog"))
        self.voivodeshipComboBoxLabel.setText(_translate("ParcelFinderDialog", "Pick voivodeship:"))
        self.countyComboBoxLabel.setText(_translate("ParcelFinderDialog", "Pick county:"))
        self.communeComboBoxLabel.setText(_translate("ParcelFinderDialog", "Pick commune:"))
        self.regionComboBoxLabel.setText(_translate("ParcelFinderDialog", "Pick region:"))
        self.parcelComboBoxLabel.setText(_translate("ParcelFinderDialog", "Pick parcel:"))
        self.parcelZoomButton.setText(_translate("ParcelFinderDialog", "Zoom"))
