# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainToolBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pluginMainToolbar(object):
    def setupUi(self, pluginMainToolbar):
        pluginMainToolbar.setObjectName("pluginMainToolbar")
        pluginMainToolbar.resize(300, 70)
        self.horizontalLayout = QtWidgets.QHBoxLayout(pluginMainToolbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uldkParcelDownloaderButton = QtWidgets.QPushButton(pluginMainToolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uldkParcelDownloaderButton.sizePolicy().hasHeightForWidth())
        self.uldkParcelDownloaderButton.setSizePolicy(sizePolicy)
        self.uldkParcelDownloaderButton.setMaximumSize(QtCore.QSize(50, 50))
        self.uldkParcelDownloaderButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uldkParcelDownloaderButton.setIcon(icon)
        self.uldkParcelDownloaderButton.setIconSize(QtCore.QSize(40, 40))
        self.uldkParcelDownloaderButton.setObjectName("uldkParcelDownloaderButton")
        self.horizontalLayout.addWidget(self.uldkParcelDownloaderButton)
        self.parcelFinderButton = QtWidgets.QPushButton(pluginMainToolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parcelFinderButton.sizePolicy().hasHeightForWidth())
        self.parcelFinderButton.setSizePolicy(sizePolicy)
        self.parcelFinderButton.setMaximumSize(QtCore.QSize(50, 50))
        self.parcelFinderButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.parcelFinderButton.setIcon(icon1)
        self.parcelFinderButton.setIconSize(QtCore.QSize(40, 40))
        self.parcelFinderButton.setObjectName("parcelFinderButton")
        self.horizontalLayout.addWidget(self.parcelFinderButton)
        self.mineralDepositCheckerButton = QtWidgets.QPushButton(pluginMainToolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mineralDepositCheckerButton.sizePolicy().hasHeightForWidth())
        self.mineralDepositCheckerButton.setSizePolicy(sizePolicy)
        self.mineralDepositCheckerButton.setMaximumSize(QtCore.QSize(50, 50))
        self.mineralDepositCheckerButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/pickaxe.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mineralDepositCheckerButton.setIcon(icon2)
        self.mineralDepositCheckerButton.setIconSize(QtCore.QSize(40, 40))
        self.mineralDepositCheckerButton.setObjectName("mineralDepositCheckerButton")
        self.horizontalLayout.addWidget(self.mineralDepositCheckerButton)
        self.basemapToggleButton = QtWidgets.QPushButton(pluginMainToolbar)
        self.basemapToggleButton.setMaximumSize(QtCore.QSize(50, 50))
        self.basemapToggleButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/stack.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.basemapToggleButton.setIcon(icon3)
        self.basemapToggleButton.setIconSize(QtCore.QSize(40, 40))
        self.basemapToggleButton.setObjectName("basemapToggleButton")
        self.horizontalLayout.addWidget(self.basemapToggleButton)
        self.settingsButton = QtWidgets.QPushButton(pluginMainToolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy)
        self.settingsButton.setMaximumSize(QtCore.QSize(50, 50))
        self.settingsButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/options.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon4)
        self.settingsButton.setIconSize(QtCore.QSize(40, 40))
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout.addWidget(self.settingsButton)

        self.retranslateUi(pluginMainToolbar)
        QtCore.QMetaObject.connectSlotsByName(pluginMainToolbar)

    def retranslateUi(self, pluginMainToolbar):
        _translate = QtCore.QCoreApplication.translate
        pluginMainToolbar.setWindowTitle(_translate("pluginMainToolbar", "Form"))
        self.uldkParcelDownloaderButton.setToolTip(_translate("pluginMainToolbar", "Download ULDK parcels"))
        self.parcelFinderButton.setToolTip(_translate("pluginMainToolbar", "Find parcel"))
        self.mineralDepositCheckerButton.setToolTip(_translate("pluginMainToolbar", "Check mineral deposit"))
        self.basemapToggleButton.setToolTip(_translate("pluginMainToolbar", "Change basemap"))
        self.settingsButton.setToolTip(_translate("pluginMainToolbar", "Plugin settings"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pluginMainToolbar = QtWidgets.QWidget()
    ui = Ui_pluginMainToolbar()
    ui.setupUi(pluginMainToolbar)
    pluginMainToolbar.show()
    sys.exit(app.exec_())
