from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QGISLayerPicker(object):
    def setupUi(self, QGISLayerPicker):
        QGISLayerPicker.setObjectName("QGISLayerPicker")
        QGISLayerPicker.setEnabled(True)
        QGISLayerPicker.resize(343, 213)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QGISLayerPicker.sizePolicy().hasHeightForWidth())
        QGISLayerPicker.setSizePolicy(sizePolicy)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(QGISLayerPicker)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.titleLabel = QtWidgets.QLabel(QGISLayerPicker)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_13.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.layerPickerTab = QtWidgets.QTabWidget(QGISLayerPicker)
        self.layerPickerTab.setEnabled(True)
        self.layerPickerTab.setObjectName("layerPickerTab")
        self.voivodeshipTab = QtWidgets.QWidget()
        self.voivodeshipTab.setEnabled(True)
        self.voivodeshipTab.setObjectName("voivodeshipTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.voivodeshipTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.voivodeshipLabel = QtWidgets.QLabel(self.voivodeshipTab)
        self.voivodeshipLabel.setObjectName("voivodeshipLabel")
        self.horizontalLayout_7.addWidget(self.voivodeshipLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.voivodeshipMapLayerComboBox = gui.QgsMapLayerComboBox(self.voivodeshipTab)
        self.voivodeshipMapLayerComboBox.setEnabled(False)
        self.voivodeshipMapLayerComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.voivodeshipMapLayerComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.voivodeshipMapLayerComboBox.setAcceptDrops(True)
        self.voivodeshipMapLayerComboBox.setObjectName("voivodeshipMapLayerComboBox")
        self.horizontalLayout_7.addWidget(self.voivodeshipMapLayerComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.voivodeshipTerytLabel = QtWidgets.QLabel(self.voivodeshipTab)
        self.voivodeshipTerytLabel.setObjectName("voivodeshipTerytLabel")
        self.horizontalLayout.addWidget(self.voivodeshipTerytLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.voivodeshipTerytFieldComboBox = gui.QgsFieldComboBox(self.voivodeshipTab)
        self.voivodeshipTerytFieldComboBox.setEnabled(False)
        self.voivodeshipTerytFieldComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.voivodeshipTerytFieldComboBox.setObjectName("voivodeshipTerytFieldComboBox")
        self.horizontalLayout.addWidget(self.voivodeshipTerytFieldComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.voivodeshipNameLabel = QtWidgets.QLabel(self.voivodeshipTab)
        self.voivodeshipNameLabel.setObjectName("voivodeshipNameLabel")
        self.horizontalLayout_6.addWidget(self.voivodeshipNameLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.voivodeshipNameFieldComboBox = gui.QgsFieldComboBox(self.voivodeshipTab)
        self.voivodeshipNameFieldComboBox.setEnabled(False)
        self.voivodeshipNameFieldComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.voivodeshipNameFieldComboBox.setObjectName("voivodeshipNameFieldComboBox")
        self.horizontalLayout_6.addWidget(self.voivodeshipNameFieldComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.layerPickerTab.addTab(self.voivodeshipTab, "")
        self.countyTab = QtWidgets.QWidget()
        self.countyTab.setEnabled(False)
        self.countyTab.setObjectName("countyTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.countyTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.countyLabel = QtWidgets.QLabel(self.countyTab)
        self.countyLabel.setEnabled(False)
        self.countyLabel.setObjectName("countyLabel")
        self.horizontalLayout_26.addWidget(self.countyLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem4)
        self.countyMapLayerComboBox = gui.QgsMapLayerComboBox(self.countyTab)
        self.countyMapLayerComboBox.setEnabled(False)
        self.countyMapLayerComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.countyMapLayerComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.countyMapLayerComboBox.setAcceptDrops(True)
        self.countyMapLayerComboBox.setObjectName("countyMapLayerComboBox")
        self.horizontalLayout_26.addWidget(self.countyMapLayerComboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.countyTerytLabel = QtWidgets.QLabel(self.countyTab)
        self.countyTerytLabel.setObjectName("countyTerytLabel")
        self.horizontalLayout_25.addWidget(self.countyTerytLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem5)
        self.countyTerytFieldComboBox = gui.QgsFieldComboBox(self.countyTab)
        self.countyTerytFieldComboBox.setEnabled(False)
        self.countyTerytFieldComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.countyTerytFieldComboBox.setObjectName("countyTerytFieldComboBox")
        self.horizontalLayout_25.addWidget(self.countyTerytFieldComboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.countyNameLabel = QtWidgets.QLabel(self.countyTab)
        self.countyNameLabel.setObjectName("countyNameLabel")
        self.horizontalLayout_27.addWidget(self.countyNameLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem6)
        self.countyNameFieldComboBox = gui.QgsFieldComboBox(self.countyTab)
        self.countyNameFieldComboBox.setEnabled(False)
        self.countyNameFieldComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.countyNameFieldComboBox.setObjectName("countyNameFieldComboBox")
        self.horizontalLayout_27.addWidget(self.countyNameFieldComboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_27)
        self.layerPickerTab.addTab(self.countyTab, "")
        self.communeTab = QtWidgets.QWidget()
        self.communeTab.setEnabled(False)
        self.communeTab.setObjectName("communeTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.communeTab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.communeLabel = QtWidgets.QLabel(self.communeTab)
        self.communeLabel.setObjectName("communeLabel")
        self.horizontalLayout_31.addWidget(self.communeLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem7)
        self.communeMapLayerComboBox = gui.QgsMapLayerComboBox(self.communeTab)
        self.communeMapLayerComboBox.setEnabled(False)
        self.communeMapLayerComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.communeMapLayerComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.communeMapLayerComboBox.setAcceptDrops(True)
        self.communeMapLayerComboBox.setObjectName("communeMapLayerComboBox")
        self.horizontalLayout_31.addWidget(self.communeMapLayerComboBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.communeTerytLabel = QtWidgets.QLabel(self.communeTab)
        self.communeTerytLabel.setObjectName("communeTerytLabel")
        self.horizontalLayout_33.addWidget(self.communeTerytLabel)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem8)
        self.communeTerytFieldComboBox = gui.QgsFieldComboBox(self.communeTab)
        self.communeTerytFieldComboBox.setEnabled(False)
        self.communeTerytFieldComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.communeTerytFieldComboBox.setObjectName("communeTerytFieldComboBox")
        self.horizontalLayout_33.addWidget(self.communeTerytFieldComboBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.communeNameLabel = QtWidgets.QLabel(self.communeTab)
        self.communeNameLabel.setObjectName("communeNameLabel")
        self.horizontalLayout_32.addWidget(self.communeNameLabel)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem9)
        self.communeNameFieldComboBox = gui.QgsFieldComboBox(self.communeTab)
        self.communeNameFieldComboBox.setEnabled(False)
        self.communeNameFieldComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.communeNameFieldComboBox.setObjectName("communeNameFieldComboBox")
        self.horizontalLayout_32.addWidget(self.communeNameFieldComboBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_32)
        self.layerPickerTab.addTab(self.communeTab, "")
        self.regionTab = QtWidgets.QWidget()
        self.regionTab.setEnabled(False)
        self.regionTab.setObjectName("regionTab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.regionTab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.regionLabel = QtWidgets.QLabel(self.regionTab)
        self.regionLabel.setObjectName("regionLabel")
        self.horizontalLayout_40.addWidget(self.regionLabel)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem10)
        self.regionMapLayerComboBox = gui.QgsMapLayerComboBox(self.regionTab)
        self.regionMapLayerComboBox.setEnabled(False)
        self.regionMapLayerComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.regionMapLayerComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.regionMapLayerComboBox.setAcceptDrops(True)
        self.regionMapLayerComboBox.setObjectName("regionMapLayerComboBox")
        self.horizontalLayout_40.addWidget(self.regionMapLayerComboBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.regionTerytLabel = QtWidgets.QLabel(self.regionTab)
        self.regionTerytLabel.setObjectName("regionTerytLabel")
        self.horizontalLayout_41.addWidget(self.regionTerytLabel)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem11)
        self.regionTerytFieldComboBox = gui.QgsFieldComboBox(self.regionTab)
        self.regionTerytFieldComboBox.setEnabled(False)
        self.regionTerytFieldComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.regionTerytFieldComboBox.setObjectName("regionTerytFieldComboBox")
        self.horizontalLayout_41.addWidget(self.regionTerytFieldComboBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.regionNameLabel = QtWidgets.QLabel(self.regionTab)
        self.regionNameLabel.setObjectName("regionNameLabel")
        self.horizontalLayout_42.addWidget(self.regionNameLabel)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem12)
        self.regionNameFieldComboBox = gui.QgsFieldComboBox(self.regionTab)
        self.regionNameFieldComboBox.setEnabled(False)
        self.regionNameFieldComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.regionNameFieldComboBox.setObjectName("regionNameFieldComboBox")
        self.horizontalLayout_42.addWidget(self.regionNameFieldComboBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_42)
        self.layerPickerTab.addTab(self.regionTab, "")
        self.parcelTab = QtWidgets.QWidget()
        self.parcelTab.setEnabled(False)
        self.parcelTab.setObjectName("parcelTab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.parcelTab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.parcelLabel = QtWidgets.QLabel(self.parcelTab)
        self.parcelLabel.setObjectName("parcelLabel")
        self.horizontalLayout_37.addWidget(self.parcelLabel)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem13)
        self.parcelMapLayerComboBox = gui.QgsMapLayerComboBox(self.parcelTab)
        self.parcelMapLayerComboBox.setEnabled(False)
        self.parcelMapLayerComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.parcelMapLayerComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.parcelMapLayerComboBox.setAcceptDrops(True)
        self.parcelMapLayerComboBox.setObjectName("parcelMapLayerComboBox")
        self.horizontalLayout_37.addWidget(self.parcelMapLayerComboBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.parcelTerytLabel = QtWidgets.QLabel(self.parcelTab)
        self.parcelTerytLabel.setObjectName("parcelTerytLabel")
        self.horizontalLayout_38.addWidget(self.parcelTerytLabel)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem14)
        self.parcelTerytFieldComboBox = gui.QgsFieldComboBox(self.parcelTab)
        self.parcelTerytFieldComboBox.setEnabled(False)
        self.parcelTerytFieldComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.parcelTerytFieldComboBox.setObjectName("parcelTerytFieldComboBox")
        self.horizontalLayout_38.addWidget(self.parcelTerytFieldComboBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.parcelNameLabel = QtWidgets.QLabel(self.parcelTab)
        self.parcelNameLabel.setObjectName("parcelNameLabel")
        self.horizontalLayout_39.addWidget(self.parcelNameLabel)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem15)
        self.parcelNameFieldComboBox = gui.QgsFieldComboBox(self.parcelTab)
        self.parcelNameFieldComboBox.setEnabled(False)
        self.parcelNameFieldComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.parcelNameFieldComboBox.setObjectName("parcelNameFieldComboBox")
        self.horizontalLayout_39.addWidget(self.parcelNameFieldComboBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_39)
        self.layerPickerTab.addTab(self.parcelTab, "")
        self.verticalLayout_13.addWidget(self.layerPickerTab)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem16)
        self.confirmButton = QtWidgets.QPushButton(QGISLayerPicker)
        self.confirmButton.setEnabled(False)
        self.confirmButton.setObjectName("confirmButton")
        self.verticalLayout_13.addWidget(self.confirmButton)

        self.retranslateUi(QGISLayerPicker)
        self.layerPickerTab.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(QGISLayerPicker)

    def retranslateUi(self, QGISLayerPicker):
        _translate = QtCore.QCoreApplication.translate
        QGISLayerPicker.setWindowTitle(_translate("QGISLayerPicker", "Dialog"))
        self.titleLabel.setText(_translate("QGISLayerPicker", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Please define plugin settings</span></p></body></html>"))
        self.voivodeshipLabel.setText(_translate("QGISLayerPicker", "Layer"))
        self.voivodeshipTerytLabel.setText(_translate("QGISLayerPicker", "Teryt"))
        self.voivodeshipNameLabel.setText(_translate("QGISLayerPicker", "Name"))
        self.layerPickerTab.setTabText(self.layerPickerTab.indexOf(self.voivodeshipTab), _translate("QGISLayerPicker", "Voivodeship"))
        self.countyLabel.setText(_translate("QGISLayerPicker", "Layer"))
        self.countyTerytLabel.setText(_translate("QGISLayerPicker", "Teryt"))
        self.countyNameLabel.setText(_translate("QGISLayerPicker", "Name"))
        self.layerPickerTab.setTabText(self.layerPickerTab.indexOf(self.countyTab), _translate("QGISLayerPicker", "County"))
        self.communeLabel.setText(_translate("QGISLayerPicker", "Layer"))
        self.communeTerytLabel.setText(_translate("QGISLayerPicker", "Teryt"))
        self.communeNameLabel.setText(_translate("QGISLayerPicker", "Name"))
        self.layerPickerTab.setTabText(self.layerPickerTab.indexOf(self.communeTab), _translate("QGISLayerPicker", "Commune"))
        self.regionLabel.setText(_translate("QGISLayerPicker", "Layer"))
        self.regionTerytLabel.setText(_translate("QGISLayerPicker", "Teryt"))
        self.regionNameLabel.setText(_translate("QGISLayerPicker", "Name"))
        self.layerPickerTab.setTabText(self.layerPickerTab.indexOf(self.regionTab), _translate("QGISLayerPicker", "Region"))
        self.parcelLabel.setText(_translate("QGISLayerPicker", "Layer"))
        self.parcelTerytLabel.setText(_translate("QGISLayerPicker", "Teryt"))
        self.parcelNameLabel.setText(_translate("QGISLayerPicker", "Name"))
        self.layerPickerTab.setTabText(self.layerPickerTab.indexOf(self.parcelTab), _translate("QGISLayerPicker", "Parcel"))
        self.confirmButton.setText(_translate("QGISLayerPicker", "Confirm"))
from qgis import gui
